server:
  port: 9200

spring:
  profiles: dev
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://imccp-management-webui.imccp
          predicates:
            - Path=/test
          filters:
            - StripPrefix=1
        - id: testStatic
          uri: http://imccp-management-webui.imccp
          predicates:
            - Path=/static/**