server:
  port: 9200

spring:
  profiles: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  cloud:
#    gateway:
#      routes:
#        - id: showurs-blog-user
#          uri: lb://showurs-blog-user
#          predicates:
#            - Path=/user