server:
  port: 9300

spring:
  http:
    encoding:
      charset: utf-8
  servlet:
    multipart:
      max-request-size: 256MB
      max-file-size: 512MB
  datasource:
    url: jdbc:mysql://localhost:3306/showurs_blog
    username: root
    password: 228136
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cache:
    redis:
      cache-null-values: false #是否允许缓存空值
      use-key-prefix: true #写入redis前是否使用密钥前缀
      time-to-live: 1h #进入到期。默认情况下，这些条目永不到期
  #      key-prefix: #blogUser: #键前缀
  redis:
    host: localhost #Redis服务器主机
    port: 6379 #redis服务器端口
    password: #登录redis服务器的密码
    timeout: 15s #连接超时
    database: 0 #连接工厂使用的数据库索引
    lettuce:
      pool:
        max-active: 8 #给定时间内池可以分配的最大连接数。使用负值无限制
        max-idle: 8 #池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接
        max-wait: -1ms #连接分配在池耗尽时抛出异常之前应阻塞的最长时间量。使用负值可以无限期地阻止
        min-idle: 0 #目标为要在池中维护的最小空闲连接数。如果该设置是肯定的，则该设置仅起作用
      shutdown-timeout: 100ms #关机超时
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
